### ISSUE TITLE
App fails when using default_avatar.

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/dionysus#116]
Suspect wrong path being passed, as avatar exists in `dionysus/dionysus_app/chart_generator/default_avatar`.
```
Please enter a chart name/title: test_chart
Traceback (most recent call last):
  File "******\dionysus\app_main.py", line 40, in <module>
    run_app()
  File "******\dionysus\app_main.py", line 34, in run_app
    run_main_menu()  # startup checks successful, enter UI.
  File "******\dionysus\dionysus_app\UI_menus\main_menu.py", line 73, in run_main_menu
    take_main_menu_input()
  File "******\dionysus\dionysus_app\UI_menus\main_menu.py", line 50, in take_main_menu_input
    possible_options[chosen_option]()
  File "******\dionysus\dionysus_app\chart_generator\create_chart.py", line 51, in new_chart
    generate_chart_image(chart_data_dict)
  File "******\dionysus\dionysus_app\chart_generator\generate_image.py", line 45, in generate_chart_image
    add_avatars_to_plot(ax, avatar_coord_dict)
  File "******\dionysus\dionysus_app\chart_generator\generate_image.py", line 114, in add_avatars_to_plot
    add_avatar_to_plot(ax, avatar_path, xy_coords)
  File "******\dionysus\dionysus_app\chart_generator\generate_image.py", line 77, in add_avatar_to_plot
    avatar_image = plt.imread(str(valid_avatar_path))  # matplotlib takes an 8bit str or FILE object, not Path object.
  File "******\Python37-64\lib\site-packages\matplotlib\pyplot.py", line 2149, in imread
    return matplotlib.image.imread(fname, format)
  File "******\Python37-64\lib\site-packages\matplotlib\image.py", line 1374, in imread
    with open(fname, 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '******\\dionysus\\chart_generator\\default_avatar.png'
```
That path should be:
`\\dionysus\\dionysus_app\\chart_generator\\default_avatar.png`
rather than:
`\\dionysus\\chart_generator\\default_avatar.png`

**Comment by toonarmycaptain** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/toonarmycaptain/dionysus/issues/21 (Build failing on all Windows builds), https://github.com/toonarmycaptain/dionysus/issues/10 (Use pathlib for filepaths), https://github.com/toonarmycaptain/dionysus/issues/86 (Use DataFolder for all data paths.), and https://github.com/toonarmycaptain/dionysus/issues/69 (Use default avatar in place of bad avatar).
